<?php

return [
    'groups' => [
        'dashboard' => 'Dashboard',
        'settings' => 'Cài đặt website',
        'content' => 'Nội dung',
        'commerce' => 'Món ăn và ưu đãi',
        'customer' => 'Khách hàng',
        'marketing' => 'Marketing và SEO',
        'system' => 'Hệ thống',
    ],

    'permissions' => [
        'dashboard.view' => ['Dashboard', 'dashboard'],

        'settings.view' => ['Xem cài đặt website', 'settings'],
        'settings.update' => ['Cập nhật cài đặt website', 'settings'],
        'identity.view' => ['Xem logo và nhận diện', 'settings'],
        'identity.update' => ['Cập nhật logo và nhận diện', 'settings'],
        'branches.view' => ['Xem cơ sở', 'settings'],
        'branches.create' => ['Thêm cơ sở', 'settings'],
        'branches.update' => ['Sửa cơ sở', 'settings'],
        'branches.delete' => ['Xóa cơ sở', 'settings'],

        'categories.view' => ['Xem danh mục', 'content'],
        'categories.create' => ['Thêm danh mục', 'content'],
        'categories.update' => ['Sửa danh mục', 'content'],
        'categories.delete' => ['Xóa danh mục', 'content'],
        'posts.view' => ['Xem bài viết', 'content'],
        'posts.create' => ['Thêm bài viết', 'content'],
        'posts.update' => ['Sửa bài viết', 'content'],
        'posts.delete' => ['Xóa bài viết', 'content'],
        'pages.view' => ['Xem trang tĩnh', 'content'],
        'pages.create' => ['Thêm trang tĩnh', 'content'],
        'pages.update' => ['Sửa trang tĩnh', 'content'],
        'pages.delete' => ['Xóa trang tĩnh', 'content'],
        'menus.view' => ['Xem menu điều hướng', 'content'],
        'menus.create' => ['Thêm menu điều hướng', 'content'],
        'menus.update' => ['Sửa menu điều hướng', 'content'],
        'menus.delete' => ['Xóa menu điều hướng', 'content'],
        'gallery.view' => ['Xem không gian quán', 'content'],
        'gallery.create' => ['Thêm ảnh không gian', 'content'],
        'gallery.update' => ['Sửa ảnh không gian', 'content'],
        'gallery.delete' => ['Xóa ảnh không gian', 'content'],

        'dishes.view' => ['Xem món ăn', 'commerce'],
        'dishes.create' => ['Thêm món ăn', 'commerce'],
        'dishes.update' => ['Sửa món ăn', 'commerce'],
        'dishes.delete' => ['Xóa món ăn', 'commerce'],
        'banners.view' => ['Xem banner', 'commerce'],
        'banners.create' => ['Thêm banner', 'commerce'],
        'banners.update' => ['Sửa banner', 'commerce'],
        'banners.delete' => ['Xóa banner', 'commerce'],
        'promotions.view' => ['Xem ưu đãi popup', 'commerce'],
        'promotions.create' => ['Thêm ưu đãi popup', 'commerce'],
        'promotions.update' => ['Sửa ưu đãi popup', 'commerce'],
        'promotions.delete' => ['Xóa ưu đãi popup', 'commerce'],
        'testimonials.view' => ['Xem review', 'commerce'],
        'testimonials.create' => ['Thêm review', 'commerce'],
        'testimonials.update' => ['Sửa review', 'commerce'],
        'testimonials.delete' => ['Xóa review', 'commerce'],

        'reservations.view' => ['Xem đặt bàn', 'customer'],
        'reservations.update' => ['Cập nhật đặt bàn', 'customer'],
        'reservations.delete' => ['Xóa đặt bàn', 'customer'],
        'contacts.view' => ['Xem liên hệ', 'customer'],
        'contacts.update' => ['Cập nhật liên hệ', 'customer'],
        'contacts.delete' => ['Xóa liên hệ', 'customer'],
        'chats.view' => ['Xem chat online', 'customer'],
        'chats.reply' => ['Trả lời chat', 'customer'],
        'chats.update' => ['Cập nhật chat', 'customer'],
        'chats.delete' => ['Xóa chat', 'customer'],

        'seo.view' => ['Xem SEO tổng thể', 'marketing'],
        'seo.update' => ['Cập nhật SEO tổng thể', 'marketing'],
        'translations.view' => ['Xem cài đặt dịch', 'marketing'],
        'translations.update' => ['Cập nhật cài đặt dịch', 'marketing'],
        'translations.auto_translate' => ['Dùng API dịch tự động', 'marketing'],

        'users.view' => ['Xem tài khoản admin', 'system'],
        'users.create' => ['Thêm tài khoản admin', 'system'],
        'users.update' => ['Sửa tài khoản admin', 'system'],
        'users.delete' => ['Xóa tài khoản admin', 'system'],
        'roles.view' => ['Xem phân quyền', 'system'],
        'roles.create' => ['Thêm vai trò', 'system'],
        'roles.update' => ['Sửa vai trò', 'system'],
        'roles.delete' => ['Xóa vai trò', 'system'],
    ],
];
